defmodule Content.CMS.Static do
  @behaviour Content.CMS

  @whats_happening [%{"changed" => [%{"value" => "1490139200"}],
       "created" => [%{"value" => "1490139146"}],
       "default_langcode" => [%{"value" => "1"}],
       "field_wh_blurb" => [%{"value" => "Looking good, is it not? Wait, I guess you're probably on this page already."}],
       "field_wh_link" => [%{"options" => [], "title" => "",
          "uri" => "https://dev.mbtace.com"}],
       "field_wh_thumb" => [%{"alt" => "A sleeping capybara", "height" => "609",
          "target_id" => "23", "target_type" => "file",
          "target_uuid" => "64a597be-e589-4446-8e15-24c66bd8b417", "title" => "",
          "url" => "http://mbta.kbox.site/sites/default/files/2017-03/qaGYucL_0.jpg",
          "width" => "553"}], "langcode" => [%{"value" => "en"}],
       "nid" => [%{"value" => "22"}], "path" => [],
       "promote" => [%{"value" => "0"}], "revision_log" => [],
       "revision_timestamp" => [%{"value" => "1490139200"}],
       "revision_translation_affected" => [%{"value" => "1"}],
       "revision_uid" => [%{"target_id" => "12", "target_type" => "user",
          "target_uuid" => "28c3025b-59e4-43c8-813b-74786413b884",
          "url" => "/user/12"}], "status" => [%{"value" => "1"}],
       "sticky" => [%{"value" => "0"}],
       "title" => [%{"value" => "Hey, check this out!"}],
       "type" => [%{"target_id" => "what_s_happening", "target_type" => "node_type",
          "target_uuid" => "f2c56f83-bc27-43e4-a54b-d8c06413f0d3"}],
       "uid" => [%{"target_id" => "12", "target_type" => "user",
          "target_uuid" => "28c3025b-59e4-43c8-813b-74786413b884",
          "url" => "/user/12"}],
       "uuid" => [%{"value" => "4a6728b4-74e5-4846-8dba-9af5eabb6858"}],
       "vid" => [%{"value" => "172"}]}]

  @all_events [%{"body" => [%{"format" => "full_html", "summary" => "",
          "value" => "<p><strong>Massachusetts Department of Transportation Meeting of the Standing Committee on Finance and Audit </strong></p>\r\n"}],
       "changed" => [%{"value" => "1490019443"}],
       "created" => [%{"value" => "1485206493"}],
       "default_langcode" => [%{"value" => "1"}],
       "field_address" => [%{"value" => "MassDOT, 10 Park Plaza\r\n\r\nTransportation Boardroom\r\n\r\nBoston, MA"}],
       "field_agenda" => [%{"format" => "basic_html",
          "value" => "<p><strong>Call to Order Chair– Betsy Taylor</strong></p>\r\n\r\n<p>&nbsp;</p>\r\n\r\n<p><strong><em>Public Comment Period</em></strong><strong><em>&nbsp;</em></strong></p>\r\n\r\n<p>&nbsp;</p>\r\n\r\n<p><strong>PROCEDURAL</strong></p>\r\n\r\n<p>&nbsp;</p>\r\n\r\n<p><strong>Approval of minutes of December 12, 2016 meeting.</strong></p>\r\n\r\n<p><strong>&nbsp;</strong></p>\r\n\r\n<p><strong>PRESENTATIONS</strong></p>\r\n\r\n<p><strong>&nbsp;</strong></p>\r\n\r\n<p>Financial Report &nbsp;from the CFO</p>\r\n\r\n<p>FY17 Budget Recast</p>\r\n\r\n<p>&nbsp;</p>\r\n\r\n<p>KPMG Discussion ofMassDOT’s FY16 Annual Report</p>\r\n\r\n<p>Update on Opportunitieson Four Highway Service Plazas</p>\r\n\r\n<p>&nbsp;</p>\r\n\r\n<p>Internal Audit</p>\r\n\r\n<p>Brockton Area Transit</p>\r\n"}],
       "field_city" => [%{"value" => "Boston"}], "field_end_time" => [],
       "field_location" => [%{"value" => "MassDOT"}],
       "field_map_address" => [%{"value" => "MassDOT, 10 Park Plaza\r\n\r\nTransportation Boardroom\r\n\r\nBoston, MA"}],
       "field_notes" => [%{"format" => "basic_html",
          "value" => "<p><strong>THIS AGENDA HAS BEEN PREPARED IN ADVANCE AND DOES&nbsp;</strong><strong>NOT NECESSARILY INCLUDE ALL MATTERS WHICH MAY BE TAKEN UP AT THIS MEETING</strong></p>\r\n"}],
       "field_start_time" => [%{"value" => "2017-01-23T15:00:00"}],
       "field_state" => [%{"value" => "MA"}],
       "field_street_address" => [%{"value" => "10 Park Plaza"}],
       "field_who" => [%{"value" => "Board Members"}],
       "langcode" => [%{"value" => "en"}], "nid" => [%{"value" => "17"}],
       "path" => [], "promote" => [%{"value" => "0"}], "revision_log" => [],
       "revision_timestamp" => [%{"value" => "1490019443"}],
       "revision_translation_affected" => [%{"value" => "1"}],
       "revision_uid" => [%{"target_id" => "10", "target_type" => "user",
          "target_uuid" => "11008298-0b5b-4491-a92c-97ae40f81a79",
          "url" => "/user/10"}], "status" => [%{"value" => "1"}],
       "sticky" => [%{"value" => "0"}],
       "title" => [%{"value" => "Finance & Audit Committee Meeting"}],
       "type" => [%{"target_id" => "event", "target_type" => "node_type",
          "target_uuid" => "db926d32-29a6-4c0b-8220-7de2c69b78c7"}],
       "uid" => [%{"target_id" => "7", "target_type" => "user",
          "target_uuid" => "d403ed87-c9e8-46d0-963f-4f9719dc599b",
          "url" => "/user/7"}],
       "uuid" => [%{"value" => "34083bf0-a9aa-4816-b247-c9c5f838bacf"}],
       "vid" => [%{"value" => "170"}]},
     %{"body" => [%{"format" => "basic_html", "summary" => "",
          "value" => "<p>The AACT board of directors meets from 10:00 AM to 12 noon and AACT members meet from 1:00 PM to 3:00 PM, on the third Wednesday of this month.</p>\r\n\r\n<p>AACT meetings are held in the State Transportation Building, 10 Park Plaza, Boston, second floor, in Conference Rooms 2 and 3, unless otherwise noted.</p>\r\n\r\n<p>To obtain a copy of this calendar in an accessible format, request special accommodations for a meeting, check on the status of a meeting, or ask any questions about AACT, please contact Janie Guion, AACT Coordinator, at 857-702-3658 (voice), 617-570-9193 (TTY), or AACT@ctps.org (email).</p>\r\n\r\n<p>THIS INFORMATION IS SUBJECT TO CHANGE.</p>\r\n"}],
       "changed" => [%{"value" => "1490019416"}],
       "created" => [%{"value" => "1481048772"}],
       "default_langcode" => [%{"value" => "1"}],
       "field_address" => [%{"value" => "MassDOT, 10 Park Plaza, Transportation Board Rm., Boston, MA 02116"}],
       "field_agenda" => [%{"format" => "basic_html",
          "value" => "<p>The AACT board of directors meets from 10:00 AM to 12 noon and AACT members meet from 1:00 PM to 3:00 PM, on the third Wednesday of this month.</p>\r\n\r\n<p>AACT meetings are held in the State Transportation Building, 10 Park Plaza, Boston, second floor, in Conference Rooms 2 and 3, unless otherwise noted.</p>\r\n\r\n<p>To obtain a copy of this calendar in an accessible format, request special accommodations for a meeting, check on the status of a meeting, or ask any questions about AACT, please contact Janie Guion, AACT Coordinator, at 857-702-3658 (voice), 617-570-9193 (TTY), or AACT@ctps.org (email).</p>\r\n\r\n<p>THIS INFORMATION IS SUBJECT TO CHANGE.</p>\r\n"}],
       "field_city" => [%{"value" => "Boston"}], "field_end_time" => [],
       "field_location" => [%{"value" => "MassDOT"}],
       "field_map_address" => [%{"value" => "10 Park Plaza, Boston, MA 02116"}],
       "field_notes" => [%{"format" => "basic_html",
          "value" => "<p>Meeting will be held in Conference Rooms 2 &amp; 3 on the second floor of the State Transportation Building.</p>\r\n"}],
       "field_start_time" => [%{"value" => "2017-03-13T16:00:00"}],
       "field_state" => [%{"value" => "MA"}],
       "field_street_address" => [%{"value" => "10 Park Plaza"}],
       "field_who" => [%{"value" => "Board Members"}],
       "langcode" => [%{"value" => "en"}], "nid" => [%{"value" => "5"}],
       "path" => [], "promote" => [%{"value" => "0"}], "revision_log" => [],
       "revision_timestamp" => [%{"value" => "1490019416"}],
       "revision_translation_affected" => [%{"value" => "1"}],
       "revision_uid" => [%{"target_id" => "10", "target_type" => "user",
          "target_uuid" => "11008298-0b5b-4491-a92c-97ae40f81a79",
          "url" => "/user/10"}], "status" => [%{"value" => "1"}],
       "sticky" => [%{"value" => "0"}],
       "title" => [%{"value" => "AACT Executive Board Meeting"}],
       "type" => [%{"target_id" => "event", "target_type" => "node_type",
          "target_uuid" => "db926d32-29a6-4c0b-8220-7de2c69b78c7"}],
       "uid" => [%{"target_id" => "1", "target_type" => "user",
          "target_uuid" => "4a887460-7f79-4e33-9f24-2cdbbbf7a4c1",
          "url" => "/user/1"}],
       "uuid" => [%{"value" => "1cc74f68-8560-4d50-a6df-ec6d7524620b"}],
       "vid" => [%{"value" => "169"}]}]

  @recent_news [%{"body" => [%{"format" => "full_html", "summary" => "",
      "value" => "<p>BOSTON -- The MBTA's Fiscal and Management Control Board (FMCB) today approved a recommendation of MBTA managers to execute a contract for construction of the brand new Blue Hill Avenue Commuter Rail Station between Blue Hill Avenue (Route 28) and Cummins Highway on the Fairmount Line. The contract will be executed with McCourt Construction Company for $16.97 million.</p>\r\n\r\n<p>Placed in a primarily residential community, Blue Hill Avenue Station will be constructed as the ninth station for the Fairmount Commuter Rail Line and provide a direct ride to downtown Boston in 20 minutes with no transfers needed. The station will be located approximately six-and-a-half miles from South Station and a quarter mile from Mattapan Square, connecting the community to other neighborhoods along the corridor. The station design includes one center-island platform between Blue Hill Avenue and Cummins Highway located below the street level measuring approximately 768 feet as well as two covered, fully accessible pedestrian ramps from both Cummins Highway and Blue Hill Avenue. The station will also include canopies, warning strips, benches/windscreens, closed circuit television (CCTV) security cameras, new lighting, new messaging signs, train approach warning systems, and historical graphic panels.</p>\r\n\r\n<p>The MassDOT Board of Directors and FMCB previously authorized funding for the project on September 2, 2015, in the amount of $26.55 million. The project was advertised in December 2016 with seven bids received. After completion of a bid analysis, the lowest bid of $16.97 million from McCourt Construction Company was chosen.</p>\r\n\r\n<p>Blue Hill Avenue Station is expected to be open along the Fairmount Line for boarding and disembarking in 2019 after a two-year construction period. On a daily basis, approximately 1,300 customers use the Fairmount Commuter Rail Line. Wachusett Station on the Fitchburg Commuter Rail Line was the last station to open in September 2016 with Boston Landing Station on the Framingham/Worcester Line scheduled to be open to passengers in April 2017.</p>\r\n"}],
       "changed" => [%{"value" => "1488904773"}],
       "created" => [%{"value" => "1485293043"}],
       "default_langcode" => [%{"value" => "1"}],
       "field_featured_image" => [%{"alt" => "Commuter Rail Train",
          "height" => "421", "target_id" => "16", "target_type" => "file",
          "target_uuid" => "21adb55b-9e49-4b3d-a40f-f94933f56430", "title" => "",
          "url" => "http://mbta.kbox.site/sites/default/files/2017-01/Allston%20train.jpg",
          "width" => "628"}],
       "field_media_contact" => [%{"value" => "MassDOT Press Office"}],
       "field_media_phone" => [%{"value" => "857-368-8500"}],
       "field_more_information" => [], "langcode" => [%{"value" => "en"}],
       "nid" => [%{"value" => "18"}], "path" => [],
       "promote" => [%{"value" => "1"}], "revision_log" => [],
       "revision_timestamp" => [%{"value" => "1488904773"}],
       "revision_translation_affected" => [%{"value" => "1"}],
       "revision_uid" => [%{"target_id" => "10", "target_type" => "user",
          "target_uuid" => "11008298-0b5b-4491-a92c-97ae40f81a79",
          "url" => "/user/10"}], "status" => [%{"value" => "1"}],
       "sticky" => [%{"value" => "0"}],
       "title" => [%{"value" => "FMCB approves Blue Hill Avenue Station on the Fairmount Line"}],
       "type" => [%{"target_id" => "news_entry", "target_type" => "node_type",
          "target_uuid" => "1944f2c9-6e14-46d1-9f16-4f54428e8f3c"}],
       "uid" => [%{"target_id" => "7", "target_type" => "user",
          "target_uuid" => "d403ed87-c9e8-46d0-963f-4f9719dc599b",
          "url" => "/user/7"}],
       "uuid" => [%{"value" => "959189aa-5a8f-44b6-bd4a-0591279da6c9"}],
       "vid" => [%{"value" => "124"}]},
     %{"body" => [%{"format" => "basic_html", "summary" => "",
          "value" => "<p>BOSTON – The MBTA today launched its Winter Weather public information campaign, urging customers to stay connected during storms and inclement weather. Commuter Rail, bus and subway riders can go to MBTA.com/winter, download a transit app and follow the T on Twitter @mbta, and sign up for T-alerts. The campaign employs digital, social and print media to encourage T riders to get the most updated service information available as they travel throughout the transit system.</p>\r\n\r\n<p>In addition to hundreds of signs inside trains and buses, winter weather messaging is being displayed on digital screens throughout the MBTA subway system. Since the record-breaking winter of 2015, the MBTA has been working to upgrade our track and signal infrastructure, investing millions in new snow-fighting equipment, as well as stocking up on replacement parts for trains.</p>\r\n\r\n<p>\"We know how important it is that our customers have the capability to access real-time information and be able to adjust their commutes accordingly,” said MBTA General Manager Brian Shortsleeve. “Our team has been working very hard to make sure thousands of T riders can get the travel information they deserve quickly and easily.”</p>\r\n\r\n<p>To help ensure that customers stay connected, the MBTA recommends the following:</p>\r\n\r\n<ul>\r\n\t<li>Visit www.mbta.com/winter</li>\r\n\t<li>Sign-up for T-Alerts</li>\r\n\t<li>Download Transit (endorsed by the MBTA)</li>\r\n\t<li>Follow us on Twitter @MBTA</li>\r\n\t<li>Call Customer Service at 617-222-3200</li>\r\n</ul>\r\n\r\n<p>The MBTA is committed to keeping its customers better informed by providing the most updated service information quickly, accurately and when they need it.</p>\r\n\r\n<p>Follow us on Twitter @MBTA for service information, and on @MBTA_CR for commuter rail service information.</p>\r\n\r\n<p>For more information on T-Alerts go to: http://www.mbta.com/rider_tools/t_alerts/</p>\r\n"}],
       "changed" => [%{"value" => "1488912845"}],
       "created" => [%{"value" => "1481039687"}],
       "default_langcode" => [%{"value" => "1"}],
       "field_featured_image" => [%{"alt" => "Proposed Government Center Head House",
          "height" => "367", "target_id" => "11", "target_type" => "file",
          "target_uuid" => "d2d6b111-7f3b-4741-8615-fde812d7bc34", "title" => "",
          "url" => "http://mbta.kbox.site/sites/default/files/2016-12/ProposedHeadHouseEntry_0.jpg",
          "width" => "670"}],
       "field_media_contact" => [%{"value" => "MassDOT Press Office"}],
       "field_media_phone" => [%{"value" => "(857) 360-8500"}],
       "field_more_information" => [%{"value" => "<p>For more information, visit <a href=\"http://www.mbta.com/rider_tools/t_alerts\">T-Alerts</a>.</p>"}],
       "langcode" => [%{"value" => "en"}], "nid" => [%{"value" => "4"}],
       "path" => [], "promote" => [%{"value" => "0"}], "revision_log" => [],
       "revision_timestamp" => [%{"value" => "1488912845"}],
       "revision_translation_affected" => [%{"value" => "1"}],
       "revision_uid" => [%{"target_id" => "10", "target_type" => "user",
          "target_uuid" => "11008298-0b5b-4491-a92c-97ae40f81a79",
          "url" => "/user/10"}], "status" => [%{"value" => "1"}],
       "sticky" => [%{"value" => "0"}],
       "title" => [%{"value" => "MBTA Urges Customers to “Stay Connected” This Winter "}],
       "type" => [%{"target_id" => "news_entry", "target_type" => "node_type",
          "target_uuid" => "1944f2c9-6e14-46d1-9f16-4f54428e8f3c"}],
       "uid" => [%{"target_id" => "1", "target_type" => "user",
          "target_uuid" => "4a887460-7f79-4e33-9f24-2cdbbbf7a4c1",
          "url" => "/user/1"}],
       "uuid" => [%{"value" => "d27fb4a2-a776-49c0-8cae-57876bc9ace8"}],
       "vid" => [%{"value" => "125"}]}]

  @basic_page %{"body" => [%{"format" => "full_html", "summary" => "",
         "value" => "<p>From accessible buses, trains, and stations, to a world-class paratransit service,&nbsp;the MBTA is dedicated to providing excellent service to customers of all abilities. We are striving to become the global benchmark for accessible public transportation—creating a system that is safe, dependable and inclusive, thereby expanding the transportation options available to all our customers, including those with disabilities.&nbsp; Select one of the links below to learn more about accessibility at the MBTA.</p>\r\n\r\n<p>If you are a person with a disability and would like to submit a reasonable modification request,&nbsp;<a href=\"http://mbtastaging.mbta.com/customer_support/?id=6442454932\">click here</a>&nbsp;to learn more.</p>\r\n\r\n<p><strong><a href=\"http://mbtastaging.mbta.com/riding_the_t/accessible_services/default.asp?id=7108\">The Office for Transportation Access--THE RIDE</a></strong><br />\r\nCustomers who are unable to use fixed-route services&nbsp; due to a disability may be eligible for MBTA paratransit service, THE RIDE.&nbsp; Click on the link above to learn more about this additional transportation option.</p>\r\n\r\n<p><strong><a href=\"http://mbtastaging.mbta.com/riding_the_t/accessible_services/default.asp?id=16901\">Department of System-Wide Accessibility</a></strong><br />\r\nEstablished in 2007, the T's Department of System-Wide Accessibility&nbsp;oversees programs and services for persons with disabilities and seniors.&nbsp; Today, the MBTA is more accessible than ever!&nbsp; Click on the link above to learn about the accessibility&nbsp;of our fixed-route services (buses, trains, and commuter boats), as well as the Department of System-Wide Accessibility.</p>\r\n\r\n<p><a href=\"http://mbtastaging.mbta.com/riding_the_t/accessible_services/default.asp?id=26302\"><strong>Access Advisory Committee to the MBTA</strong></a><br />\r\nThe Access Advisory Committee to the MBTA is a consumer body composed primarily of persons with disabilities. Customers, advocates and representatives of disability advocacy groups and agencies advise and make recommendations to the MBTA regarding accessible transportation for both its Fixed Route services (buses, subway and trains) and its Paratransit program, THE RIDE. Anyone is invited to participate. To learn more click on the link above.</p>\r\n"}],
      "changed" => [%{"value" => "1484163899"}],
      "created" => [%{"value" => "1482874857"}],
      "default_langcode" => [%{"value" => "1"}], "field_downloads" => [],
      "langcode" => [%{"value" => "en"}], "nid" => [%{"value" => "6"}],
      "path" => [], "promote" => [%{"value" => "0"}], "revision_log" => [],
      "revision_timestamp" => [%{"value" => "1484163899"}],
      "revision_translation_affected" => [%{"value" => "1"}],
      "revision_uid" => [%{"target_id" => "7", "target_type" => "user",
         "target_uuid" => "d403ed87-c9e8-46d0-963f-4f9719dc599b",
         "url" => "/user/7"}], "status" => [%{"value" => "1"}],
      "sticky" => [%{"value" => "0"}],
      "title" => [%{"value" => "Accessibility at the T"}],
      "type" => [%{"target_id" => "page", "target_type" => "node_type",
         "target_uuid" => "9e4b5efa-9303-469e-b5d6-20ef12fbe1d1"}],
      "uid" => [%{"target_id" => "7", "target_type" => "user",
         "target_uuid" => "d403ed87-c9e8-46d0-963f-4f9719dc599b",
         "url" => "/user/7"}],
      "uuid" => [%{"value" => "a53215a8-b83a-4503-a349-7b54dbb07564"}],
      "vid" => [%{"value" => "75"}]}

  @project_update %{"body" => [%{"format" => "basic_html", "summary" => "",
         "value" => "<p>Value Engineering (VE), managed by the Owner′s Representative as required by MGL 30/39M.5, was performed in January 2011. The major recommendation of the study was to close Government Center Station to patrons (but allow trains to pass through) for twenty-four months during the construction period by diverting passengers to other nearby stations. Closure/bypass of the station to patrons for twenty-four months during construction eliminates the need for a temporary head house and allows construction to proceed more rapidly, thereby resulting in the overall delivery of accessibility to be achieved earlier. The closure also results in minimization of system delays, improved worker and public safety, and improved construction quality. The recommendation was presented to the MBTA Board of Directors in April 2011. The Board concurred with that recommendation, and design progressed based on the Station being closed as recommended.</p>\r\n"}],
      "changed" => [%{"value" => "1489597382"}],
      "created" => [%{"value" => "1480612626"}],
      "default_langcode" => [%{"value" => "1"}],
      "field_downloads" => [%{"description" => "Government Center Presentation",
         "display" => "1", "target_id" => "10", "target_type" => "file",
         "target_uuid" => "0227954f-b10f-4c86-b0de-5fed18a63051",
         "url" => "http://mbta.kbox.site/sites/default/files/2016-12/Gov%20Center%20Station%20Presentation.pdf"}],
      "field_featured_image" => [%{"alt" => "Proposed Government Center Head House",
         "height" => "368", "target_id" => "9", "target_type" => "file",
         "target_uuid" => "98365781-b78f-48dc-8acc-7c5f25f0b05c", "title" => "",
         "url" => "http://mbta.kbox.site/sites/default/files/2016-12/ProposedStationHeadHouse.jpg",
         "width" => "667"}],
      "field_photo_gallery" => [%{"alt" => "Government Center during construction",
         "height" => "2322", "target_id" => "7", "target_type" => "file",
         "target_uuid" => "499a208a-31f5-4913-b2ef-8dbbe2065d36", "title" => "",
         "url" => "http://mbta.kbox.site/sites/default/files/2016-12/Gov%20Center%20Photo%201%281%29.jpg",
         "width" => "4128"},
       %{"alt" => "Proposed Government Center Head House entry", "height" => "2322",
         "target_id" => "8", "target_type" => "file",
         "target_uuid" => "14d879c9-3470-4daa-8782-94473d2331d0", "title" => "",
         "url" => "http://mbta.kbox.site/sites/default/files/2016-12/ProposedHeadHouseEntry.jpg",
         "width" => "4128"}], "field_status" => [%{"value" => "Construction"}],
      "langcode" => [%{"value" => "en"}], "nid" => [%{"value" => "3"}],
      "path" => [], "promote" => [%{"value" => "0"}], "revision_log" => [],
      "revision_timestamp" => [%{"value" => "1489597382"}],
      "revision_translation_affected" => [%{"value" => "1"}],
      "revision_uid" => [%{"target_id" => "10", "target_type" => "user",
         "target_uuid" => "11008298-0b5b-4491-a92c-97ae40f81a79",
         "url" => "/user/10"}], "status" => [%{"value" => "1"}],
      "sticky" => [%{"value" => "0"}],
      "title" => [%{"value" => "Government Center Construction"}],
      "type" => [%{"target_id" => "project_update", "target_type" => "node_type",
         "target_uuid" => "5d44d0a5-a17b-409b-b222-58c333623cbd"}],
      "uid" => [%{"target_id" => "1", "target_type" => "user",
         "target_uuid" => "4a887460-7f79-4e33-9f24-2cdbbbf7a4c1",
         "url" => "/user/1"}],
      "uuid" => [%{"value" => "173f23c7-facf-4a45-91ec-0c73221e5c3b"}],
      "vid" => [%{"value" => "129"}]}

  def view(path, params \\ [])
  def view("/whats_happening", _) do
    {:ok, @whats_happening}
  end
  def view("/events", opts) do
    results = case Keyword.get(opts, :id) do
      nil -> @all_events
      id -> Enum.filter(@all_events, & match?(%{"nid" => [%{"value" => ^id}]}, &1))
    end

    {:ok, results}
  end
  def view("/recent-news", _) do
    {:ok, @recent_news}
  end
  def view("/accessibility", _) do
    {:ok, @basic_page}
  end
  def view("/gov-center-project", _) do
    {:ok, @project_update}
  end
  def view("/news/winter", _) do
    {:ok, @recent_news |> List.first}
  end
  def view(_, _) do
    {:error, {"Didn't work", "Sorry"}}
  end
end
