
name: Jest with comments!
on: pull_request
env:
  MIX_ENV: test

jobs:
  jest:
    name: Javascript unit tests
    runs-on: ubuntu-latest 

    steps:
    - uses: actions/checkout@v2
    ############
    # Use all the cached stuff.
    ###########
    - name: <asdf> Restore cache
      uses: actions/cache@v2
      with:
        path: ~/.asdf
        key: ${{ runner.os }}-asdf-v2-${{ hashFiles('.tool-versions') }}
    - name: <asdf> Set env vars
      run: |
        ASDF_DIR=$HOME/.asdf
        echo "ASDF_DIR=$ASDF_DIR" >> $GITHUB_ENV
        echo "ASDF_DATA_DIR=$ASDF_DIR" >> $GITHUB_ENV
        echo "$ASDF_DIR/bin" >> $GITHUB_PATH
        echo "$ASDF_DIR/shims" >> $GITHUB_PATH
    - name: <elixir> Restore dependencies cache
      uses: actions/cache@v2
      with:
        path: deps
        key: ${{ runner.os }}-mix-${{ hashFiles('**/mix.lock') }}
        restore-keys: ${{ runner.os }}-mix-
    - name: <node> Restore dependencies cache
      uses: actions/cache@v2
      with:
        path: "apps/site/*/node_modules"
        key: ${{ runner.os }}-nodejs-${{ hashFiles('apps/site/*/package-lock.json') }}
        restore-keys: ${{ runner.os }}-nodejs-
    ############
    # Build the application
    ###########  
    - run: ./semaphore/build_app.sh
      shell: bash
    ############
    # Run Jest tests with annotations
    ###########
    - name: Jest test
      uses: mattallty/jest-github-action@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        V3_URL: ${{ secrets.V3_URL}}
        V3_API_KEY: ${{ secrets.V3_API_KEY }}
      with:
        changes-only: true
        test-command: "npm run test:jest -- --json --outputFile="jest.results.json"
