# Every change to master, we recreate/refresh caches so they're available later

name: Setup and cache Dotcom languages and deps
on:
  push:
    branches:
    - master
env:
  MIX_ENV: test

jobs:
  setup_all:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: <asdf> Restore cache of languages from .tool-versions
      uses: actions/cache@v2
      with:
        path: ~/.asdf
        key: ${{ runner.os }}-asdf-v2-${{ hashFiles('.tool-versions') }}
      id: asdf-cache
    - name: <asdf> Install languages from .tool-versions (if needed)
      uses: asdf-vm/actions/install@v1
      if: steps.asdf-cache.outputs.cache-hit != 'true'
    - name: <asdf> Set env vars
      run: |
        ASDF_DIR=$HOME/.asdf
        echo "ASDF_DIR=$ASDF_DIR" >> $GITHUB_ENV
        echo "ASDF_DATA_DIR=$ASDF_DIR" >> $GITHUB_ENV
        echo "$ASDF_DIR/bin" >> $GITHUB_PATH
        echo "$ASDF_DIR/shims" >> $GITHUB_PATH

    - name: <elixir> Restore dependencies cache
      uses: actions/cache@v2
      with:
        path: deps
        key: ${{ runner.os }}-mix-${{ hashFiles('**/mix.lock') }}
        restore-keys: ${{ runner.os }}-mix-
      id: elixir-cache
    - name: <elixir> Install dependencies (if needed)
      if: steps.elixir-cache.outputs.cache-hit != 'true'
      run: |
        mix local.hex --force
        mix local.rebar --force
        mix deps.get

    - name: <node> Restore dependencies cache
      uses: actions/cache@v2
      with:
        path: "apps/site/*/node_modules"
        key: ${{ runner.os }}-nodejs-${{ hashFiles('apps/site/*/package-lock.json') }}
        restore-keys: ${{ runner.os }}-nodejs-
      id: node-cache
    - name: <node> Install dependencies (if needed)
      if: steps.node-cache.outputs.cache-hit != 'true'
      run: |
        git config --global url."https://github.com/".insteadOf ssh://git@github.com/
        npm run install:ci && npm run react:setup:ci
